// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwv4V6pqv8SjqQ19l-pYUljXm7ChmwSRk',
    appId: '1:482642256450:web:ab77a62e05f70ee166c3db',
    messagingSenderId: '482642256450',
    projectId: 'bookshelf-app-cb465',
    authDomain: 'bookshelf-app-cb465.firebaseapp.com',
    storageBucket: 'bookshelf-app-cb465.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0GnX7k7A8RvPB3R2f2lfMES3GLvGgkOU',
    appId: '1:482642256450:android:f0cdc45accc8a56766c3db',
    messagingSenderId: '482642256450',
    projectId: 'bookshelf-app-cb465',
    storageBucket: 'bookshelf-app-cb465.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcYSedwD7a27RZ5z8yofCpTTjUhiFv5XI',
    appId: '1:482642256450:ios:2f91efff4c7c4c7266c3db',
    messagingSenderId: '482642256450',
    projectId: 'bookshelf-app-cb465',
    storageBucket: 'bookshelf-app-cb465.firebasestorage.app',
    iosBundleId: 'com.example.bookshelfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcYSedwD7a27RZ5z8yofCpTTjUhiFv5XI',
    appId: '1:482642256450:ios:2f91efff4c7c4c7266c3db',
    messagingSenderId: '482642256450',
    projectId: 'bookshelf-app-cb465',
    storageBucket: 'bookshelf-app-cb465.firebasestorage.app',
    iosBundleId: 'com.example.bookshelfApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwv4V6pqv8SjqQ19l-pYUljXm7ChmwSRk',
    appId: '1:482642256450:web:fa2c608574efd7b466c3db',
    messagingSenderId: '482642256450',
    projectId: 'bookshelf-app-cb465',
    authDomain: 'bookshelf-app-cb465.firebaseapp.com',
    storageBucket: 'bookshelf-app-cb465.firebasestorage.app',
  );

}